### ISSUE TITLE
Object tracking without canvas element?

### ISSUE THREAD

**Issue by animdan** [cloud-annotations/mosse-pixel-tracker#33]
Am wondering, is it possible to not use a canvas element since for my application I don't need to display the selection borders while tracking? I just need to fetch the selection rectangle position coordinates (perhaps created with a visible colored div border or SVG border via mouse selection marquee) as it invisibly (display:none) tracks the object on a video. Any thoughts?

**Comment by bourdakos1** [comment]
You don’t need to use canvas. The api gives you coordinates per frame and then you can decide what to do with them

**Comment by animdan** [comment]
Neat, I'll dig deeper and see what else I can do. Thx.
